# Generated by Django 6.0.5 on 2026-05-15 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='emal',
            new_name='email',
        ),
    ]
