# Generated by Django 6.0.5 on 2026-06-20 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0002_rename_emal_candidate_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='gaps',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='stengths',
            field=models.TextField(blank=True),
        ),
    ]
