# Generated by Django 6.0.5 on 2026-06-20 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0003_candidate_gaps_candidate_stengths'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='stengths',
            new_name='strengths',
        ),
    ]
